// THE RANKING. The ORDER of this list is the ranking — the player at the top is
// #1, the next is #2, and so on. To reorder, just move lines up or down, then
// run `npm run rank` to stamp the new ranks into every content/players/*.md.
//
// `name`  → shown on the site, also used to build the slug + filename.
// `wiki`  → OPTIONAL. Only when the Wikipedia article title differs from the
//           name (a disambiguation, e.g. "Sam Jones"). Used by `npm run players`.
export const players = [
  { name: 'Michael Jordan' },
  { name: 'LeBron James' },
  { name: 'Kareem Abdul-Jabbar' },
  { name: 'Magic Johnson' },
  { name: 'Bill Russell' },
  { name: 'Wilt Chamberlain' },
  { name: 'Larry Bird' },
  { name: 'Tim Duncan' },
  { name: 'Kobe Bryant' },
  { name: "Shaquille O'Neal" },
  { name: 'Hakeem Olajuwon' },
  { name: 'Oscar Robertson' },
  { name: 'Jerry West' },
  { name: 'Kevin Durant' },
  { name: 'Stephen Curry' },
  { name: 'Moses Malone' },
  { name: 'Julius Erving' },
  { name: 'Karl Malone' },
  { name: 'Charles Barkley' },
  { name: 'David Robinson', wiki: 'David Robinson (basketball)' },
  { name: 'Kevin Garnett' },
  { name: 'Dirk Nowitzki' },
  { name: 'Elgin Baylor' },
  { name: 'John Stockton' },
  { name: 'Scottie Pippen' },
  { name: 'Giannis Antetokounmpo' },
  { name: 'Isiah Thomas' },
  { name: 'Patrick Ewing' },
  { name: 'Dwyane Wade' },
  { name: 'Allen Iverson' },
  { name: 'Steve Nash' },
  { name: 'Jason Kidd' },
  { name: 'Gary Payton' },
  { name: 'Chris Paul' },
  { name: 'John Havlicek' },
  { name: 'Rick Barry' },
  { name: 'Bob Pettit' },
  { name: 'George Mikan' },
  { name: 'Clyde Drexler' },
  { name: 'James Harden' },
  { name: 'Nikola Jokić' },
  { name: 'Pete Maravich' },
  { name: 'Walt Frazier' },
  { name: 'Willis Reed' },
  { name: 'Wes Unseld' },
  { name: 'Dave Cowens' },
  { name: 'Bob Cousy' },
  { name: 'Dominique Wilkins' },
  { name: 'Reggie Miller' },
  { name: 'Ray Allen' },
  { name: 'Paul Pierce' },
  { name: 'Kawhi Leonard' },
  { name: 'Russell Westbrook' },
  { name: 'Anthony Davis' },
  { name: 'Damian Lillard' },
  { name: 'Carmelo Anthony' },
  { name: 'Tracy McGrady' },
  { name: 'Vince Carter' },
  { name: 'Pau Gasol' },
  { name: 'Tony Parker' },
  { name: 'Manu Ginóbili' },
  { name: 'Chris Webber' },
  { name: 'Alonzo Mourning' },
  { name: 'Dikembe Mutombo' },
  { name: 'Robert Parish' },
  { name: 'Kevin McHale', wiki: 'Kevin McHale (basketball)' },
  { name: 'James Worthy' },
  { name: 'Dennis Rodman' },
  { name: 'Bernard King' },
  { name: 'Connie Hawkins' },
  { name: 'Elvin Hayes' },
  { name: 'Nate Thurmond' },
  { name: 'Bob McAdoo' },
  { name: 'Earl Monroe' },
  { name: 'Dave DeBusschere' },
  { name: 'Sam Jones', wiki: 'Sam Jones (basketball, born 1933)' },
  { name: 'Hal Greer' },
  { name: 'Lenny Wilkens' },
  { name: 'Dolph Schayes' },
  { name: 'Paul Arizin' },
  { name: 'Bill Sharman' },
  { name: 'Nate Archibald' },
  { name: 'Dave Bing' },
  { name: 'Chris Mullin', wiki: 'Chris Mullin (basketball)' },
  { name: 'Joe Dumars' },
  { name: 'Grant Hill', wiki: 'Grant Hill (basketball)' },
  { name: 'Ben Wallace', wiki: 'Ben Wallace (basketball)' },
  { name: 'Chauncey Billups' },
  { name: 'Bill Walton' },
  { name: 'Adrian Dantley' },
  { name: 'Spencer Haywood' },
  { name: 'Jerry Lucas' },
  { name: 'Yao Ming' },
  { name: 'Klay Thompson' },
  { name: 'Draymond Green' },
  { name: 'Kyrie Irving' },
  { name: 'Joel Embiid' },
  { name: 'Luka Dončić' },
  { name: 'Paul George' },
  { name: 'Jimmy Butler' },
]
